# Generated by Django 6.0.4 on 2026-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tecnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to=None, verbose_name='tecnologies/')),
            ],
            options={
                'verbose_name': 'tecnologies',
                'verbose_name_plural': 'tecnologies',
            },
        ),
    ]
