# Generated by Django 6.0.4 on 2026-05-04 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.URLField(verbose_name='Image')),
                ('live_link', models.URLField()),
                ('github_link', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=50))),
            ],
        ),
    ]
